version: 2.1
executors:
  base-php:
    environment:
      - WP_TEST_URL: "http://localhost:12000"
      - DB_USER: "user"
      - DB_PASSWORD: "passw0rd"
      - DB_NAME: "test_db"
    docker:
      - image: circleci/php:7.1-apache-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd


jobs:
  build:
    executor: base-php
    steps:
      - checkout
      - restore_cache: 
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache: 
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

  lint:
    executor: base-php
    steps:
      - checkout
      - restore_cache: 
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer run-script lint

  test:
    executor: base-php
    steps:
      - checkout
      - restore_cache: 
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run: sudo apt-get install mysql-client
       
      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            
      - run: chmod +x wp-cli.phar
            
      - run: ./wp-cli.phar core download --allow-root --path=wordpress
            
      - run: ./wp-cli.phar core config --allow-root --dbname=$DB_NAME --dbuser=$DB_USER --dbpass=$DB_PASSWORD --dbhost=127.0.0.1 --path=wordpress
            
      - run: ./wp-cli.phar core install --allow-root --admin_name=$WP_TEST_USER --admin_password=WP_TEST_USER_PASS --admin_email=admin@example.com --url=$WP_TEST_URL --title=WordPress --path=wordpress
            
      - run: composer run-script wp-package
            
      - run: ./wp-cli.phar plugin install poet.zip --path=wordpress --activate

      - store_artifacts:
          path: poet.zip

dependencies:
  pre:


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build

