version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: composer run-script lint

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
